### ISSUE TITLE
I find anyone who find this problem :unauthorized access to "libmedia.so"

### ISSUE THREAD

**Issue by MountainNine** [ViktorDegtyarev/CallRecLib#11]
When I start, pause, and resume this sample app, this popup message is represented:

Detected Problem with app native libraries
(Please consult log for details):
libcallrecfix.so: unauthorized access to "libmedia.so"

And When I start the record and finish the phone call, the file is saved with .WAV file, and it doesn't have any sounds

What's the problem?

**Comment by developer--** [comment]
same for me with Android O

**Comment by MountainNine** [comment]
solved.

**Comment by thelittlefireman** [comment]
Could you please share your solution ?

**Comment by MountainNine** [comment]
In my case, just build app in release version.
