### ISSUE TITLE
Error while loading libutils.so

### ISSUE THREAD

**Issue by KnightOfRealm** [ViktorDegtyarev/CallRecLib#5]
While loading your library, I am getting error on loading libutils.so .I am new to NDK, so don't know much
Error log: 

I/CallRecLib: Error: dlopen failed: library "libutils.so" not found
02-06 18:11:12.960 21141-21141/com.superreceptionist W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
02-06 18:11:12.960 21141-21141/com.superreceptionist W/google-breakpad: Chrome build fingerprint:
02-06 18:11:12.960 21141-21141/com.superreceptionist W/google-breakpad: 2.6.2
02-06 18:11:12.960 21141-21141/com.superreceptionist W/google-breakpad: 158
02-06 18:11:12.960 21141-21141/com.superreceptionist W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
02-06 18:11:12.960 21141-21141/com.superreceptionist A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 21141 (perreceptionist)
                                                             
                                                             [ 02-06 18:11:12.961   454:  454 W/         ]
                                                             debuggerd: handling request: pid=21141 uid=10275 gid=10275 tid=21141

**Comment by KnightOfRealm** [comment]
issue was in my gradle and project not in the library.

**Comment by tkharishankar** [comment]
Hi @KnightOfRealm 
am also facing same issue.
could please help me to fix this issue.

- Added the library
- changed the package name in audio.cpp,callrecfix.cpp.

is anything i missed?

**Comment by samehali1998** [comment]
[Requests.zip](https://github.com/ViktorDegtyarev/CallRecLib/files/4198715/Requests.zip)
